FROM rockylinux:8

RUN dnf check-update; dnf update -y; dnf install -y dnf-plugins-core epel-release; dnf install -y 'dnf-command(config-manager)'; dnf config-manager --set-enabled powertools; dnf update -y
RUN dnf install -qy wget python3 postgresql postgresql-contrib postgresql-server

COPY *.rpm setup_phobos.sh launch_container_services.sh phobos.conf /
RUN dnf install -y phobos*.$(arch).rpm hestia*.$(arch).rpm

COPY ./config/hestia.yaml /configs/
RUN ./setup_phobos.sh phobos.conf /home/phobos_test_dir phobos_test_dir

ENTRYPOINT ["./launch_container_services.sh"]