cache_path: /cache

server:
  host: 127.0.0.1
  tag: s3_controller0
  interfaces: 
    - type: s3
      port: 8090
      enable_auth: false
    - type: http
      port: 8080

tiers:
  - id: "00000000-0000-0000-0000-000000000001"
    priority: 0

object_store_backends:
  - backend_type: file
    tiers: 
      ids: ["00000000-0000-0000-0000-000000000001"]
    config: 
      root: s3_server_object_store

logger:
  level: info